- name: Setup LAMP Stack on Ubuntu
  hosts: web
  become: yes
  tasks:
    - name: Update and upgrade packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install Apache and PHP
      apt:
        name:
          - apache2
          - php
          - libapache2-mod-php
        state: present

    - name: Install MySQL server
      apt:
        name: mysql-server
        state: present

    - name: Deploy website file
      copy:
        src: ./website/index.php
        dest: /var/www/html/index.php

    - name: Set permissions for web root
      file:
        path: /var/www/html
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Ensure Apache is running
      service:
        name: apache2
        state: started
        enabled: yes

